[package]
name = "harmonia"
version = "1.0.0"
edition = "2021"

[dependencies]
clap = "4.0"
walkdir = "2.3"
dirs = "4.0"
whoami = "1.2"
rodio = "0.14"
hound = "3.4"

[[bin]]
name = "harmonia"
path = "src/main.rs"
